# Generated by Django 5.1.1 on 2024-10-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_projectresource_month_projectresource_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='actual_resource',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
