# Generated by Django 5.1.1 on 2024-10-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_projectresource_actual_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresource',
            name='actual_resource',
            field=models.FloatField(),
        ),
    ]
